export default [
  {
    name: "Organic Tomatoes",
    description: "Fresh organic tomatoes from our farm",
    price: 2.5,
    quantity: 100,
    category: "Vegetables",
    images: ["uploads/tomatoes.jpg"],
    harvestDate: new Date("2023-06-15"),
    isOrganic: true,
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "Sweet Corn",
    description: "Sweet and juicy corn",
    price: 1.8,
    quantity: 200,
    category: "Grains",
    images: ["uploads/corn.jpg"],
    harvestDate: new Date("2023-06-20"),
    isOrganic: false,
    rating: 4.2,
    numReviews: 8,
  },
  {
    name: "Strawberries",
    description: "Fresh red strawberries",
    price: 3.5,
    quantity: 50,
    category: "Fruits",
    images: ["uploads/strawberries.jpg"],
    harvestDate: new Date("2023-06-10"),
    isOrganic: true,
    rating: 4.8,
    numReviews: 15,
  },
  {
    name: "Carrots",
    description: "Organic carrots",
    price: 1.2,
    quantity: 150,
    category: "Vegetables",
    images: ["uploads/carrots.jpg"],
    harvestDate: new Date("2023-06-05"),
    isOrganic: true,
    rating: 4.0,
    numReviews: 5,
  },
  {
    name: "Apples",
    description: "Juicy red apples",
    price: 2.0,
    quantity: 120,
    category: "Fruits",
    images: ["uploads/apples.jpg"],
    harvestDate: new Date("2023-06-25"),
    isOrganic: false,
    rating: 4.3,
    numReviews: 12,
  },
];
