export default [
  {
    name: "John Farmer",
    email: "john@example.com",
    password: "123456",
    phone: "1234567890",
    address: "123 Farm St, Farmville",
    role: "farmer",
    bankDetails: {
      accountName: "John Farmer",
      accountNumber: "123456789",
      bankName: "Farmers Bank",
      branch: "Farmville",
    },
    isVerified: true,
  },
  {
    name: "Jane Farmer",
    email: "jane@example.com",
    password: "123456",
    phone: "0987654321",
    address: "456 Orchard Rd, Farmtown",
    role: "farmer",
    bankDetails: {
      accountName: "Jane Farmer",
      accountNumber: "987654321",
      bankName: "Farmers Bank",
      branch: "Farmtown",
    },
    isVerified: true,
  },
  {
    name: "Market Vendor",
    email: "vendor@example.com",
    password: "123456",
    phone: "5551234567",
    address: "789 Market St, Cityville",
    role: "vendor",
    isVerified: true,
  },
  {
    name: "Supermarket Vendor",
    email: "supermarket@example.com",
    password: "123456",
    phone: "5557654321",
    address: "321 Mall Rd, Bigcity",
    role: "vendor",
    isVerified: true,
  },
  {
    name: "Delivery Driver",
    email: "driver@example.com",
    password: "123456",
    phone: "5559876543",
    address: "654 Truck Ave, Transport City",
    role: "driver",
    isVerified: true,
  },
  {
    name: "Truck Driver",
    email: "trucker@example.com",
    password: "123456",
    phone: "5554567890",
    address: "987 Highway Blvd, Transit Town",
    role: "driver",
    isVerified: true,
  },
];
